services:
  backend:
    build: ./api
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    networks:
      - app_network

  frontend:
    build: ./front-end-nextjs 
    container_name: react-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
