name: Deploy to AWS S3 & Run Docker Compose

on:
  push:
    branches:
      - main  # Runs on push to the main branch

jobs:
  deploy:
    name: Deploy to AWS S3
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy Website to S3
        run: |
          aws s3 sync ./front-end-nextjs s3://${{ secrets.S3_BUCKET_NAME }} --delete

      - name: Verify Deployment
        run: |
          aws s3 ls s3://${{ secrets.S3_BUCKET_NAME }}

  docker-compose:
    name: Run Docker Compose
    runs-on: ubuntu-latest
    needs: deploy  # Runs after S3 deployment

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io docker-compose

      - name: Run Docker Compose
        run: |
          docker-compose up -d
