name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger the pipeline on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Replace with your Python version

      # Step 3: Install dependencies
      - name: Install backend dependencies
        run: |
          cd api
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 5: Build Docker images
      - name: Build Docker images
        run: |
          docker compose build

      # Step 6: Build the frontend
      - name: Build frontend 
        run: |
          cd front-end-nextjs  # Navigate to your frontend directory
          npm install
          npm run dev  # Build the frontend (replace with your build command)

      # Step 7: Deploy frontend to S3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Replace with your AWS region

      - name: Deploy frontend to S3
        run: |
          aws s3 sync frontend/build s3://devops-qr-code-project --delete
